---
title: "Glider Lab Manual"
subtitle: "Ecosystem Science Division, NMFS/SWFSC"
page-layout: full
---

The Ecosystem Science Division (ESD) at the [Southwest Fisheries Science Center](https://www.fisheries.noaa.gov/about/southwest-fisheries-science-center) does some pretty cool stuff using gliders. This website is an in-development manual for all ESD glider activities. The current website outline/working doc is [here](https://docs.google.com/document/d/1F1nxoBkeEcXmXGOOioQHqD6A_KIdJmDsg9P_Nfe5Y-o/edit?usp=sharing).\
Funding for the glider lab comes from base funding of the ESD (SOS, AMLR, and WIND), with additional funding from the NOAA IRA strategic initiatives; UXS-OC (REFOCUS etc.).

## Team Members

| Name                                               | Job Title                                  |
|------------------------------------|------------------------------------|
| [Christian Reiss](mailto:christian.reiss@noaa.gov) | Glider Team PI, Offshore Wind Program Lead |
| [Anthony Cossio](mailto:anthony.cossio@noaa.gov)   | Lab Manager, Operations Research Analyst   |
| [Jen Walsh](mailto:jen.walsh@noaa.gov)             | Fisheries Research Biologist               |
| [JC Clark](mailto:jason.c.clark@noaa.gov)          | NOAA Corps                                 |
| [Caleb Flaim](mailto:caleb.flaim@noaa.gov)         | Electronics Technician                     |
| [Jacob Partida](mailto:jacob.partida@noaa.gov)     | Physical Science Technician                |
| [Hailey Schmidt](mailto:hailey.schmidt@noaa.gov)   | Glider Pilot                               |
| [Sam Woodman](mailto:sam.woodman@noaa.gov)         | Data Manager                               |
| [Heidi Taylor](mailto:heidi.taylor@noaa.gov)       | ESD Deputy Director, SOS Program Lead      |
| [George Watters](mailto:george.watters@noaa.gov)   | ESD Director                               |

## Project Management

For most current Fleet Status information, see [this Sheet](https://docs.google.com/spreadsheets/d/1tB3QNKYx8qOYYS9QZotekBAx0y-_n2d-EZPjFFdYNuU/edit?usp=sharing)

The ESD glider team is using GitHub Issues and Projects for project management. There efforts are heavily inspired and influenced by the Openscapes [GitHub for project management](https://openscapes.github.io/series/core-lessons/github/github-issues.html) approach.

To view the ESD glider team project, see [here](https://github.com/orgs/us-amlr/projects/1). This project pulls from issues from several repositories, but in particular [this repo](https://github.com/us-amlr/glider-lab). For more details see TODO (section under development in glider lab qmd file).

## GitHub Repositories

GitHub repos developed by the ESD glider team:

| repo link                                                                       | description                                                                                     |
|------------------------------------|------------------------------------|
| [glider-lab](https://github.com/us-amlr/glider-lab)                             | Repo for tracking ESD glider lab issues/tasks                                                   |
| [standard-glider-files](https://github.com/us-amlr/standard-glider-files)       | ESD glider cache files, as well as standard files that are put on all gliders before deployment |
| [glider-utils](https://github.com/SWFSC/glider-utils)                           | Utility functions for processing ESD glider data                                                |
| [echoview_glider_template](https://github.com/us-amlr/echoview_glider_template) | Echoview glider templates that are used for acoustic data analysis                              |
| [glider_processing_code](https://github.com/us-amlr/glider_processing_code)     | Compilation of code that is used to work with glider acoustic data                              |
| [glider-lab-manual](https://github.com/SWFSC/glider-lab-manual)                 | ESD glider lab website                                                                          |

<br /> Most relevant external repos:

| repo link                                                                       | description                                                                                                                                                     |
|------------------------------------|------------------------------------|
| [dbdreader](https://github.com/smerckel/dbdreader)                              | Extract data from slocum binary files                                                                                                                           |
| [pyglider](https://github.com/c-proof/pyglider)                                 | Convert datafiles from slocum and seaexplorer into netcdf                                                                                                       |
| [SOCIB glider toolbox](https://github.com/socib/glider_toolbox)                 | Process slocum, seaglider and seaxplorer data in Matlab (unsupported)                                                                                           |
| [GliderTools](https://github.com/GliderToolsCommunity/GliderTools)              | Quality control and plot generic glider data                                                                                                                    |
| [IOOS qc](https://github.com/ioos/ioos_qc)                                      | Apply IOOS QARTOD and other qc routines                                                                                                                         |
| [glider tools list](https://github.com/OceanGlidersCommunity/glider-tools-list) | [OceanGliders community](https://github.com/OceanGlidersCommunity) repository to list tools for processing glider data. Includes many of the tools listed here. |

## Deployments

The below table lists all ESD (and formerly AERD) glider deployments. For accessing glider data, see [Data Management](content/data-management.qmd)

Table todo, a la [this sheet](https://docs.google.com/spreadsheets/d/1tSIi44OTEUQXPJwwiy1emhdIyRs9Vt8iT5IlJBMrPLA/edit?usp=sharing)
