---
title: Best Practices
---

::: callout-note
## Note

This is a living document which shall always be considered a "draft," as incoming and veteran members of the lab may want to contribute ideas or revisions. This is a place to begin, a place to return to, a place to ground ongoing conversations. Modeled after https://sael-swfsc.github.io/SAEL-lab-manual/content/SharedValues-BestPractices.html
:::


## **ESD Glider Lab Best Practices**

### **Communication**

1.  We hold lab meetings regularly in which all members are expected to attend if their schedule allows. During these meetings all members are expected to contribute by sharing progress reports, discussing challenges, and celebrating successes.

2.  We use Google Meet for informal discussions between lab members and project teams. 

3.  We use Github projects to keep track of tasks and projects. All lab members are expected to check & respond to email, chats, and Github Projects regularly.

### **Safety**

1.  Lab members are expected to follow all safety protocols. If they are not sure of the protocol, then they should request this information.

2.  Lab members should never feel obligated to perform a task that they do not feel is safe.

3.  Lab members are encouraged to speak up if they feel they need training to perform a specific task safely.

4.  If lab members have a safety concern, they should bring it up with their supervisor or the other lab members.

5.  If a lab member feels their safety concerns are not being taken seriously, or have any other lab safety questions, they can consult the acting SWFSC Safety Officer Ariane Huddleston ([ariane.huddleston@noaa.gov](mailto:ariane.huddleston@noaa.gov)).

### **Website Development**

As described above, this website is intended to be a place for all glider team members to both use as a reference and contribute to. This section contains development notes and best practices

1. If using VSCode, [this page](https://quarto.org/docs/tools/vscode.html) contains helpful references and shortcuts. One of the most common and important is to [render and preview](https://quarto.org/docs/tools/vscode.html#render-and-preview) the current qmd files, which you can do with the <kbd>Ctrl+Shift+K</kbd> keyboard shortcut.