---
title: Glider Lab
---

This page contains various procedures and resources for glider lab members, including ESD standard operating procedures, manuals, training documents, and contract info. For piloting tools, see [Glider Pilot Tools](pilot-tools.qmd). 

[Gliders and Mooring Google Calendar](https://calendar.google.com/calendar/embed?src=noaa.gov_v9l4l68ihu9n2svmno3tk1qvec%40group.calendar.google.com&ctz=America%2FLos_Angeles){target="_blank"}

## Standard Operating Procedures

[Glider Checkout Procedure](https://docs.google.com/document/d/1FdrB_BeSkKoy3XOzIwfmd_sm7aAwoaeT9AQfz0bkh8A/edit){target="_blank"} The steps needed to prepare a glider for deployment.

[How to upgrade the glider operating system](https://docs.google.com/document/d/1fospbDFkPfeCtmj6wJtINlZGb13-bkNIAn2fKB5Ek1s/edit){target="_blank"}

[How to calibrate the AZFP](https://docs.google.com/document/d/10sJRgIOPb4awRG6GcpJIfy7RDksZSbjWxIXCW1Xk1Qw/edit){target="_blank"}

[How to calibrate the compass on the glider](https://docs.google.com/document/d/1Ny_K8jxSWA71vFyzvtJ7bK2i5aDPo2gu/edit?usp=sharing&ouid=102683297276185841842&rtpof=true&sd=true){target="_blank"}

[How to calibrate the shadowgraph](https://docs.google.com/document/d/1M9s7rSlgdBHxFnBTdKWelLfpMghZU3p8K5TImlIJ8FI/edit){target="_blank"}

How to talk to the camera (shadowgraph or glidercam)

How to set up the Nortek compact echosounder

[How ESD pilots a glider](https://docs.google.com/document/d/1nPnl30IcK-sAbd-i1x3YUq--M43Z5XNxo1Eev1fYsJM/edit?usp=sharing){target="_blank"} (also  see [How Jen deploys a glider](https://docs.google.com/document/d/1nHKAF2F_UOV8gzQ825N7KCo8QvZ-3XBhDxQDVqCU6Po/edit?usp=sharing){target="_blank"})

[How to use the high speed data cable](https://docs.google.com/document/d/10WD0RvmtD3B5yXnNhMeQiUxuK524cDntec29c57cEyI/edit?usp=sharing){target="_blank"}

[Steps for deploying a glider](https://docs.google.com/document/d/1bxen4GvXxmZZoXP24-Mn_2fjzKx7fJx0l_CkeGul-oI/edit){target="_blank"}

[Tony's SFMC Data Visualizations](https://docs.google.com/document/d/1GgaZyglCF5wDOZruK5Ewc5HsKpwMg3jxkPrCb9s_g4k/edit?usp=sharing){target="_blank"}

[Notes on Nortek mini-echosounder](https://docs.google.com/document/d/11ih0V16ZixwDb9c7f-6vLbt-bbhiwrVagAG_7VGKJaU/edit?usp=sharing){target="_blank"}

[How to work on a glider while it is open](https://docs.google.com/document/d/1a_N0zhSXgMQSYMxEsWwzVrb4hMajXvOHCJinXlJvthc/edit?usp=sharing){target="_blank"}


## Online Calculators

[Sea Water Density](https://fermi.jhuapl.edu/denscalc.html){target="_blank"} - Calculate sea water density and sound speed.

### Calculators for Acoustics

[Sound Absorption](http://resource.npl.co.uk/acoustics/techguides/seaabsorption/){target="_blank"} - Calculate Absorption using the Francois and Garrison, 1982 method.

[Standard Sphere Target Strength](https://www.fisheries.noaa.gov/data-tools/standard-sphere-target-strength-calculator){target="_blank"} - Standard sphere target strength calculator created by Advanced Survey Technologies, SWFSC.

## Manuals

### **Slocum**


[Slocum Fleet Mission Control 2019](https://drive.google.com/file/d/15n3mQmRP0_HTuUXbMi6hEEYOIGd81sb5/view?usp=drive_link){target="_blank"}

[Slocum G3 Glider Operators Manual 2019](https://drive.google.com/file/d/1qQWFOZMSv8FQZmk8_7XItLFRQ1CCArOd/view?usp=drive_link){target="_blank"}

[Slocum G3 Maintenance Manual 2019](https://drive.google.com/file/d/1NHIC_bQe2xjB3sw42vuT_aK9cup8pQAF/view){target="_blank"}

[Slocum G3S New Processor Guide 2021 Draft B](https://drive.google.com/file/d/1nfxGecTRVpzeVXK3owIZv7FprvylL2W_/view){target="_blank"}

### **Cameras**

[Shadowgraph r3](https://drive.google.com/file/d/1Ns-b0VmK9DmwB6rKtL0uP9s6vl4i2PLE/view?usp=sharing){target="_blank"}

[Glidercam r2.1](https://drive.google.com/file/d/1TwuEmq_5PADnZ080sjW02Yltb2_E-VOd/view){target="_blank"}

### **Nortek compact echosounder**

[Integrators guide 2024](https://drive.google.com/file/d/1alDzxEH2y8qRiVK84he_lmzSYe_p5PEo/view?usp=drive_link){target="_blank"}

[Signature 100 Operations Manual 2022](https://drive.google.com/file/d/10xkj3nGJSlXBlI_0imdwU-7tYl-BJ4ok/view?usp=drive_link){target="_blank"}

[Principles of Operations Signature 100 2022](https://drive.google.com/file/d/1lU-GrL2S-lRS9ta9jJPRC23KoUZtvVXa/view?usp=drive_link){target="_blank"}

[MIDAS software User Guide 2019](https://drive.google.com/file/d/1rMces9zavoaGUGz_UseJERyQcwnMqI0Q/view?usp=drive_link){target="_blank"}

### **AZFP Acoustic Zooplankton Fish Profiler**

[AZFPLink Software 2019](https://drive.google.com/file/d/1lapjSo5PowFz3hg0titXKRKw43TzE6PQ/view?usp=drive_link){target="_blank"}

[AZFP Glider Operators Manual 2020](https://drive.google.com/file/d/1oUlWwatlenKCCb098wAQ3-PNIiiZ3rDk/view?usp=drive_link){target="_blank"}

[AZFP Operators Manual 2019](https://drive.google.com/file/d/1PCRZJ798CCKfaZSdjb_OOFqtmLCqSmiJ/view?usp=drive_link){target="_blank"}

### **ECOPuck**

[ECOPuck User Manual 2017](https://drive.google.com/file/d/1-qq2GU-LoJZYq1lxHMppllWFkgy4y70d/view?usp=drive_link){target="_blank"}

### **AAnderaa Oxygen Optode**

[Oxygen Optode Manual 2017](https://drive.google.com/file/d/1-etHx8dsXKcp6XoSZG9PtV2HXbDQHTbv/view?usp=drive_link){target="_blank"}

### **Biospherical Par Sensor**
[QSP-2150 submersible Par Manual](https://drive.google.com/file/d/1iFpBvCYvnX0WQOrN65xoAA9qzebTGjfM/view?usp=sharing){target="_blank"}

### **WISPR Passive Acoustic Monitoring**

[WISPR 3 Github](https://github.com/embeddedocean/wispr3){target="_blank"}

### **DMON**
[DMON instructions](https://drive.google.com/file/d/1B0qPXvF9vondThmoCeFgc_b4TiKmtLQX/view?usp=drive_link){target="_blank"}

[DMON software and settings](https://drive.google.com/drive/folders/1iRRukFoOWjqd1ezeZGp7gapMBgFmJK73?usp=drive_link){target="_blank"}


## Software and settings

Add info on setting up a glider field laptop so they are all set up the same way.

| Software                                                                                       | Settings |  Use                                                                                            |
|------------------------------|------------------------------|------------------------------|
| [ZOC](https://www.emtec.com/zoc/index.html){target="_blank"}                                                    | [Settings](https://docs.google.com/document/d/1lDMAtfzKKY7XLKwakii6P_g1HGAFZYtKUMWhLEW4DUU/edit?usp=sharing){target="_blank"} | Talking with the glider over Freewave |
| [Tera Term](https://teratermproject.github.io/index-en.html){target="_blank"}                                   | Settings | Talking with the camera |                                                                                  |
| [AZFP](https://drive.google.com/file/d/16eSSKX3DGkA6UUvign7KnQwzPqhUJHil/view?usp=drive_link){target="_blank"}  | Settings |  Calibrating and settings for AZFP|                                                                                          |
| [MIDAS](https://drive.google.com/file/d/1lGYgthRRTBOQShaTqlrB233jWfp_uRZV/view?usp=drive_link){target="_blank"} | Settings | Setting up Nortek |                                                                                            |
| [WinSCP](https://winscp.net/eng/index.php){target="_blank"}                                                     | Settings | FTP client for the camera |                                                                                            |
| [Notepad++](https://notepad-plus-plus.org/){target="_blank"}                                                    | Settings  | Changing and reading glider files |  
| [OceanContour](https://oceanillumination.com/){target="_blank"}												 | Settings  | For viewing ADCP data |                                                                                       |

## Parts List
Where we buy specific parts

[O-rings](documents/O-rings.md){target="_blank"}

## Training Documents

[Slocum Basic Training Slides May 2024](https://drive.google.com/file/d/15O-BuBtiOovHT-yFzKEvVNwmOnNgvnjW/view?usp=drive_link){target="_blank"}

[Slocum Basic Training Slides May 2024 Materials](https://drive.google.com/drive/folders/1TFtmFJRK5apAygQBu0I0FzWULkcj0Wuq?usp=drive_link){target="_blank"}

[Slocum Advanced Training 2019 Materials](https://drive.google.com/drive/folders/1J3KsCSu_GY0ig4K4oV3MvDlINFPDyqim?usp=drive_link){target="_blank"}

[Rutgers Glider Camp 2023](https://drive.google.com/drive/folders/1cx8iuoX5duVvjwIw6RTQChlb1mFERctT?usp=drive_link){target="_blank"}

## Contracts

[Outer Limits 2024-28](https://drive.google.com/file/d/10IzLqGHu_7d6_8tS502Z2ny15joWZ_Sh/view?usp=drive_link){target="_blank"} Charter boat out of Mission Bay BPA [site](https://www.outerlimit.net/){target="_blank"}

[Pacific Venture 2024-28](https://drive.google.com/file/d/1RBtK_C4E4CEsA-l35DK0bf7-PqMbhuud/view?usp=drive_link){target="_blank"} Charter boat out of Oceanside BPA [site](https://www.pacific-venture.com/){target="_blank"}

[Teledyne Webb Research 2024-28](https://drive.google.com/file/d/1_8WzrrVxbi9TgE-HvbDqZZI5n8mLUHuH/view?usp=drive_link){target="_blank"} IDIQ for Slocum gliders and parts [site](https://www.teledynemarine.com/brands/webb-research/){target="_blank"}

## Glider and Mooring Database

You can find the Glider and Mooring Database on the network drive under AMLR_Datasets. The database is a SQL server database with an Access front end, accessible over the SWFSC network (including VPN). It is used to track several facets of gliders, including glider builds, deployments, and the number of deployment days and inflections for various sensors. We are working on scripts to get some standard data out as well as populate yml files for archiving deployment data. For more information see [Data Management](data-management.qmd). 
